services:
  database:
    image: postgis/postgis
    container_name: database_doctor
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: doctor
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
